### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by denisr-w** [ng-select/ng-select#1317]
**Describe the bug**
I have an angular app with a component which has `encapsulation` set to `ViewEncapsulation.ShadowDom`. Inside the template of this component I'm using a `ng-select` component. Through `items` input I'm passing 15 items to `ng-select` component.

I'm getting an error in the console when:
- I click `ng-select` component and scroll down in the dropdown
- I click `ng-select` component, select one of the first top items in the dropdown and then click on it again.

Error that I'm getting is:
`Uncaught TypeError: Cannot read property 'scrollTop' of null`

Through my testing I have noticed that this error appears when:
- a component with `encapsulation` set to `ViewEncapsulation.ShadowDom` is using a `ng-select` component in its template and
- is passing to it an array of items long enough that it creates a scroll bar in a dropdown

I'm setting `encapsulation` to `ViewEncapsulation.ShadowDom` because this solves some problems when I'm using the component for `@angular/elements`.

**Reproducible example**
[Example](https://github.com/denisr-w/ng-select-test) which reproduces described behaviour

**To Reproduce** 
1. Clone or download the repository provided in reproducible example
2. Build and serve the app using `ng serve` command
3. Do the steps described above

**Comment by benoitjchevalier** [comment]
Hello,

we're also encountering the same issue when using `ViewEncapsulation.ShadowDom`/Angular Elements

**Comment by bartes** [comment]
same issue here when using ViewEncapsulation.ShadowDom

`File webpack:///./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js.pre-build-optimizer.js line 2264 col 53 in l._next
(e) => this._onContentScrolled(e.target.scrollTop)));`

**Comment by nikkonduru88** [comment]
Hi. Thanks for an awesome package and all the work. Is there an update on this issue?

**Comment by nikkonduru88** [comment]
@varnastadeus Hi. Hope you are doing well. I was debugging this issue and found that instead of using e.target.scrollTop in ng-dropdown-panel.component.ts, if we use e.path[0].scrollTop, it works for both ViewEncapsulation.ShadowDom and normally. Do you see any concern in switching it to path[0] instead of target? I can create a PR if you are okay with it. Thanks again! :)

**Comment by nikkonduru88** [comment]
@varnastadeus Thanks for reopening the issue. Are you looking into testing and creating a PR for the potential fix or you want me to do it? If we fix it, it will only be for 3.x version right? Since there are no more 2.x versions added for Angular 7. We need to update our Angular to Angular 8+?

**Comment by ianhyun007** [comment]
Hi, I have same issue with using using ViewEncapsulation.ShadowDom.

If there is any solutions to this, please let me know too, thank you.

**Comment by nikkonduru88** [comment]
@varnastadeus Hi. Hope you are doing well. I created a PR to fix this issue, but I think there are some issues with unit test that is not related to my code. I think the PR before me has the same issue. Can you review the PR when you get a chance. Thanks again for awesome work. 👍

**Comment by nikkonduru88** [comment]
@varnastadeus I created a PR to fix this issue. Can you please review it when you get a chance. I am getting unit test failure that is not related. Thank you.

**Comment by snehal4it** [comment]
Looks like issue is fixed only in master.
We are still using angular8 so is there any plan to apply this fix to 3.x branch (and other branches)?

**Comment by mhubertm** [comment]
Issue still exists...

**Comment by rnd4994** [comment]
Any update on this? Currently experiencing the issue in chrome when using angular elements and ng-select v~7.

**Comment by nettags** [comment]
The error also exists in (current) Version 10.0.4 of ng-select with Angular 15.2.x  with enabled ViewEncapsulation.ShadowDom.

I'm pretty sure the error was fixed before but is back since several versions, but it may also be that I have not noticed it.

Please re-open the issue again. Thx!

**Comment by kmiasko** [comment]
Can confirm that the bug still exists inside ShadowDom elements.

```
~/... (... ✗) npm list @ng-select/ng-select
...@0.0.0 /...
├── @ng-select/ng-select@10.0.4
```

```
zone.js:182 Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')
    at Object.next (ng-select-ng-select.mjs:1599:73)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at endDuration (audit.js:17:28)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at AnimationFrameAction.<anonymous> (timer.js:23:28)
    at AnimationFrameAction._execute (AsyncAction.js:56:18)
    at AnimationFrameAction.execute (AsyncAction.js:44:28)
    at AnimationFrameScheduler.flush (AnimationFrameScheduler.js:11:33)
    at AnimationFrameAction.js:14:125
    at timer (zone.js:2405:41)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
```

**Comment by lrphael** [comment]
Same problem with the same version

**Comment by s-torrisi** [comment]
Still having the same problem, any update?

**Comment by lrphael** [comment]
> Still having the same problem, any update?

I fixed this problem myself. I had to copy the entire component from the library (in the version I need) to my project and then I fix by my self the scrollTop error (just a missing validation).
It has been working
