### ISSUE TITLE
Wrong dropdown height with virtualScroll if first element in ng-select is " "

### ISSUE THREAD

**Issue by mibjg** [ng-select/ng-select#1402]
**Describe the bug**
If the first element in the ng-select is a space, it seems like the height of the dropdown is calculated based on a smaller row-height than the rest of the elements.
This only happens if virtualScroll is true

**Reproducbile example**
https://stackblitz.com/edit/angular-wpjuge

**Expected behavior**
I expected the dropdown to have the same height as if the first element had contained text

**Desktop:**
 - OS: Windows 10
 - Browser chrome
 - Version 77.0.3865.120

**Comment by rh-silpion** [comment]
It's not just a problem if the first element is a space.

If `virtualScroll` is enabled, `ng-dropdown-panel.component.ts` gets the height of the first option item in `_measureDimensions()` with:

```typescript
const option = this._dropdown.querySelector(`#${first.htmlId}`);
const optionHeight = option.clientHeight;
this._virtualPadding.style.height = `${optionHeight * this.itemsLength}px`;
const panelHeight = this._scrollablePanel.clientHeight;
this._panelService.setDimensions(optionHeight, panelHeight);
```

All height calculations are then performed with this first option height value. Different heights of the options items are currently not possible/ignored.

I think the idea behind this decision was to improve the performance. But is it really a huge performance effort to calculate the height just for the visible options items? 
It would be great if we can change/fix this. Because, if the first option item is higher then the others, we have a visible jump every time an option item is added or removed from the `.scrollable-content` div.

**Comment by rh-silpion** [comment]
Here is an example: https://stackblitz.com/edit/angular-hvpqyh

We have a jump between `Test3` and `Test4`. And not all `Test` items are visible. Not visible are `Test18`, `Test19`, `Test20`.

**Comment by mivanyna** [comment]
I guess one of the simplest fixes would be adding css like:
`
.ng-option {
        height: 36px;
}
`

**Comment by rh-silpion** [comment]
Absolutely right. It helps, but only if all options have the same height. It does not work for dynamic heights.

**Comment by varnastadeus** [comment]
fixed in v5.0.12

**Comment by marwgit** [comment]
We have in our project version 6.1.0 and this is still happening.

If first element has a long text and takes up multiple lines, then it fixes the height for all the following elements. This leads to a couple of remaining unused empty lines at the bottom of the list.
