### ISSUE TITLE
Ng-select inside dialog add extra hidden height (dropdown)

### ISSUE THREAD

**Issue by aitboudad** [ng-select/ng-select#240]
demo: https://stackblitz.com/edit/angular-material2-issue-yesgfz

### Expected behaviour

example using material select:
![selection_113](https://user-images.githubusercontent.com/1753742/35924646-81d5dc74-0c1b-11e8-932d-e863eab2f858.png)

### Actual behaviour
using ng-select:
![selection_112](https://user-images.githubusercontent.com/1753742/35924670-9445194c-0c1b-11e8-85c4-99a54e434068.png)

### More Info
ng-select version: 0.19.0

**Comment by anjmao** [comment]
@aitboudad Thanks for good repro. It works fine in bootstrap 4 modal window, but I will have a look that is wrong here.

**Comment by anjmao** [comment]
@aitboudad In new 0.23 version dropdown panel is not append to the DOM by default anymore, it should fix this issue.

**Comment by rpascal** [comment]
@aitboudad I believe the issue is still there. Please see https://stackblitz.com/edit/angular-material2-issue-jqdq7v with the latest version.

**Comment by aitboudad** [comment]
@rpascal yes, the solution is to use `[appendTo]="'body'"`

**Comment by dbjar** [comment]
ng-select dropdown does not work propperly when it is rendered inside content where the overflow is set to 'hidden'.

The overflow of the angular material dialog has set its overflow to 'auto'. In order to change this, I've found the following topic on stackoverflow: https://stackoverflow.com/questions/46271898/overriding-angular-material-size-and-styling-of-md-dialog-container 

Overlay-based components have a panelClass property (or similar) that can be used to target the overlay pane.

You can override the default dialog container styles by adding a css class in your global styles.css. For 

```
.custom-dialog-container .mat-dialog-container {
    overflow: visible;
}
```
After that, you'll need to providies you css class as a panelClass parameter to your dialog:

`this.dialog.open(MyDialogComponent, { panelClass: 'custom-dialog-container' })`

**Comment by sarancreators** [comment]
quick fix :

.mat-dialog-content, ..mat-dialog-container{overflow: visible !important;}
.mat-dialog-actions{clear: both;}

**Comment by jpike88** [comment]
@sarancreators works like a charm. not sure what the side-effects might be... I don't notice any for now

**Comment by saurabh1etech** [comment]
Quick Fix

**Comment by saurabh1etech** [comment]
Quick Fix,

**Comment by saurabh1etech** [comment]
quick fix,
appendTo="ng-select"

**Comment by jpike88** [comment]
@saurabh1etech that would not work for me as the parent container has overflow which would hide the ng-select. appendTo="body" is what I need to use

**Comment by saurabh1etech** [comment]
@jpike88 You can use it in case you are using ng-select inside a popup

**Comment by stefann01** [comment]
This worked for me:
.custom-dialog-container .mat-dialog-container,
.custom-dialog-container .mat-dialog-content {
  overflow: visible;
}

**Comment by williamreyesmiranda** [comment]
this worked for me
1. added appendTo `<ng-select **[appendTo]="'body'"**>...</ng-select>`
2. in css added: `::ng-deep .ng-dropdown-panel {
     z-index: 9999999!important;
 }`

**Comment by JoshMLeslie** [comment]
For posterity:
It seems the selectors have shifted somewhat. The previous class names have migrated to attributes and now the css reads as
```
.custom-dialog-container {
  .mat-mdc-dialog-content,
  .mat-mdc-dialog-surface {
    overflow: visible;
  }
}
```
