### ISSUE TITLE
ng-option  signal value must be extra checked with "20.2.0"

### ISSUE THREAD

**Issue by kle-pra** [ng-select/ng-select#2674]
### Describe the bug

I have a use case where organizations() is a signal what changes asynchronously and it's value is used to show  ng-options:

```html
 <ng-select
      [(ngModel)]="org"
      [disabled]="!projectUi"
      @for (o of organizations(); track o.id) {
        <ng-option [value]="o">{{ o.name }}</ng-option>
      }
    </ng-select>
```

With updating to 20.1.3 -> 20.2.0 I get error: 

```
chunk-SLTR3U3Z.js:85 TypeError: Cannot set properties of undefined (setting 'disabled')
    at Object.next (ng-select-ng-select.mjs:3379:14)
    at tap.js:17:81
    at OperatorSubscriber2._this._next (OperatorSubscriber.js:15:21)
    at Subscriber2.next (Subscriber.js:34:18)
    at mergeInternals.js:25:28
    at OperatorSubscriber2._this._next (OperatorSubscriber.js:15:21)
    at Subscriber2.next (Subscriber.js:34:18)
    at Subject.js:41:34
```

If I check signal value with @if before lopping, it works again, but this was not necessary in previous version. Is this a bug or expected behaviour? 

This works:
```html
@if(organizations()) {
  @for (o of organizations(); track o.id) {
        <ng-option [value]="o">{{ o.name }}</ng-option>
      }
}
```

### Steps to Reproduce

/

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

/

### Expected behaviour

```html
 <ng-select
      [(ngModel)]="org"
      [disabled]="!projectUi"
      @for (o of organizations(); track o.id) {
        <ng-option [value]="o">{{ o.name }}</ng-option>
      }
    </ng-select>
```

### What version of the library you see this issue?

20.2.0

### What version of Angular are you using?

Angular 20

**Comment by ilyakonrad** [comment]
Facing the same issue. It's either a bug or some sort of breaking change. Has to be patched.

**Comment by pavankjadda** [comment]
tagging @pankajparkar

**Comment by pavankjadda** [comment]
@kle-pra @ilyakonrad share a stackblitz link and use the work around for the moment

**Comment by pankajparkar** [comment]
I will take a look @pavankjadda

**Comment by pankajparkar** [comment]
Stackblitz repro - https://stackblitz.com/edit/angular-zumcy3tx?file=src%2Fmain.ts

```
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <ng-select
      [(ngModel)]="org"
      [disabled]="!projectUi">
      @for (o of organizations(); track o.id) {
        <ng-option [value]="o">{{ o.name }}</ng-option>
      }
    </ng-select>
  `,
  imports: [NgSelectModule, FormsModule],
})
export class App {
  projectUi = true;
  org = 1;

  organizations = signal([
    { id: 1, name: 'Test 1' },
    { id: 2, name: 'Test 2' },
  ]);

  ngOnInit() {
    // Setting asynchronously
    setTimeout(() => {
      this.organizations.set([
        { id: 1, name: 'Test 1' },
        { id: 2, name: 'Test 2' },
        { id: 3, name: 'Test 3' },
      ]);
    }, 3000);
  }
}

bootstrapApplication(App);
```

**Comment by terencehonles** [comment]
I believe this is fixed by my PR https://github.com/ng-select/ng-select/pull/2690 and is the same issue in https://github.com/ng-select/ng-select/issues/2688

**Comment by adam-marshall** [comment]
my ng-selects started hanging after upgrading to the latest version during migration to Angular 20.

I downgraded to ^20.0.0 and now the hang is gone

**Comment by kle-pra** [comment]
Is there any progress on this? 

I noticed after latest updates, there is no error thrown in browser console anymore, but the bug remains - it can be reproduced in https://github.com/ng-select/ng-select/issues/2674#issuecomment-3266473058 example if ng-select is updated to latest.

Extra if check remains the workaround.
