### ISSUE TITLE
Allow disabling of browser autocomplete

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#269]
Please fill below information if issuing a bug report. 
### Expected behaviour
Set the autocomplete attribute of the input field to "off", or allow passing it as an optional attribute so the search would work better.

### Actual behaviour
right now the search results has double dropdown. One by the browser autocomplete, and one by the ng-select. looks wierd.

![ss](https://user-images.githubusercontent.com/5073214/36296996-4a3b7a1a-1316-11e8-8c6a-a9f264963a49.jpg)

### More Info
ng-select version: latest

browser: Chrome
reproducible in demo page: Yes

**Comment by varnastadeus** [comment]
@arun-maddheshia I think it should be disabled by default. Will fix it.

**Comment by arun-maddheshia** [comment]
@varnastadeus thanx :+1:  when it get it release :)

**Comment by varnastadeus** [comment]
@arun-maddheshia later today

**Comment by arun-maddheshia** [comment]
@varnastadeus autocomplete off is not working in chrome :(
![screenshot_2018-02-18_16-28-07](https://user-images.githubusercontent.com/5073214/36351027-f4913ea6-14c8-11e8-88eb-f42a119d2184.png)

**Comment by varnastadeus** [comment]
As it seems chrome ignores autocomplete off, but if you provide any semantic value then it will work. Not sure about other browsers though

**Comment by arun-maddheshia** [comment]
@varnastadeus so what workaround to do with ng select because if user autofills the search field its get broken. User unable to select the ng-select dropdown values.

**Comment by dan-andreoli** [comment]
@varnastadeus with the last chrome update (v64.x) the workaround not working anymore, but I've noticed that the autocomplete doesn't break the select, but it only hide the selected value. Here a simple solution: ass to the css class .ng-select { z-index: -1; } and this solves the hiding problem.

**Comment by arun-maddheshia** [comment]
@varnastadeus any update on it, the issue is still exist. 
@dan-andreoli  `.ng-select { z-index: -1; }` is not solved the problem.

**Comment by varnastadeus** [comment]
@arun-maddheshia please provide reproducible plnkr, I tried to reproduce it with no luck.

**Comment by arun-maddheshia** [comment]
@varnastadeus Just create a [StackBlitz](https://stackblitz.com/edit/angular-ng-select)

![screenshot_2018-03-11_22-55-55](https://user-images.githubusercontent.com/5073214/37256406-491bce56-2580-11e8-918f-9902354766bc.png)

**Comment by varnastadeus** [comment]
@arun-maddheshia thanks, will look at it

**Comment by pwarelis** [comment]
To disable (fool) the autofill you need to set the input name attribute to something that chrome has not seen before and has no history of. Try uuid.

**Comment by anjmao** [comment]
As https://github.com/ng-select/ng-select/commit/30201c000c50e9ae74addd11d549c58a970a2f1a is merged now we have newId function which can be used on input name.

**Comment by arun-maddheshia** [comment]
@anjmao can we fix it please :)

**Comment by anjmao** [comment]
@arun-maddheshia have you looked at https://stackoverflow.com/questions/12374442/chrome-browser-ignoring-autocomplete-off? Setting `<form autocomplete="off">` should solve this problem for you :)

**Comment by varnastadeus** [comment]
@arun-maddheshia I have added id as autocomplete value.

**Comment by przemkow** [comment]
@varnastadeus, unfortunately, it does not solve the problem. Chrome autofill still pops up on my browser.

Chrome: Version 67.0.3396.87 (Official Build) (64-bit)
ng-select: 1.5.2

**Comment by unit147** [comment]
Chrome: Version 68.0.3440.106 (Official Build) (64-bit)
ng-select: 2.5.1 is not usable because of this bug :(

**Comment by DonJuwe** [comment]
@varnastadeus, if I change it to `autocomplete="off"` manually in _Chrome Version 69.0.3497.100 (64-Bit)_ it works. Could you please change it?

**Comment by varnastadeus** [comment]
instead of saying it doesn't work, create reproducible example proving it

**Comment by vmanchev** [comment]
What I found for this bug and Chrome is that the **labelForId** is problematic. 

- if **labelForId** is not used, the problem does not exists. You'll lose some usability though, as when you click on the form label, the ng-select control will not be focused.
- if **labelForId** is used with some common name (like "client" in my case), Chrome will do its best to provide browser autocomplete.
- if **labelForId** is used with unique value (e.g. "client123"), there will be no browser autocomplete

**Comment by DonJuwe** [comment]
As @vmanchev mentioned, `labelForId` seems to be the problem since it is being converted to a property `id` of the generated `<input>`. [Here is a StackBlitz](https://stackblitz.com/edit/ng-select-srgafm?file=app/app.component.ts) which the current version (2.11.1) where you can reproduce the issue when you have values stored in your browser for an `<input>` with property `id="city"`. 
This triggers the browser's autocomplete like here: 
![2018-10-24 16_54_48-ng-select - stackblitz](https://user-images.githubusercontent.com/22655540/47440322-351a5680-d7ae-11e8-9739-ef94720e550e.png)
By manually changing `autocomplete` to `off` for the generated `<input>` Chrome's **autocomplete** will not be triggered.

**Comment by Lars-Wunderlich** [comment]
Urgently needed and helpful....

**Comment by smasala** [comment]
@DonJuwe workaround:

```typescript
ngOnInit() {
      setTimeout( () => {
        document.querySelector('ng-select input[autocomplete]').setAttribute('autocomplete', 'off');
      });
}
```

**Comment by Xyaren** [comment]
@varnastadeus This should be reopened as the bug still exists, as prooven in the example provided by @DonJuwe

**Comment by varnastadeus** [comment]
Ok I have it reproducible so I will check it out. I will try to see if `autocomple="off"` works while `labelForId` is applied

**Comment by esoyke** [comment]
@smasala I used a similar approach but instead set the autocomplete value to something nonsensical ('foobar'), as it seems autocomplete=off was being ignored by Chrome now.

**Comment by dela1000** [comment]
Running into this myself. using ngTagsInput v3.2.0. Adding `<tags-input autocomplete="off">` does not work. 

I do see that the $templateCache includes that already `<input class=\"input\" autocomplete=\"off\" `

**Comment by bharatlagad** [comment]
@varnastadeus... Have you updated autocomplete = "off" on npm

**Comment by sarnecki-cic** [comment]
My workaround was to change input id in ngAfterViewInit() and adding timpestamp there:

```
ngAfterViewInit(): void {
        document.querySelector('input[data-name=ng-select]').id = 'newId-' + this.timestamp;
    }
```

**Comment by Ogunk** [comment]
Hi, I'm still having this issue and tried everything here and other places but nothing is working.

Here is my code : 

```
      <label for="ppp">Organization</label>
      <ng-select [hideSelected]="true" autocomplete="off" placeholder="Select an organization" labelForId="ppp"
        [closeOnSelect]="true" [searchable]="true" formControlName="organizationId">
        <ng-option *ngFor="let organization of availableOrganizations" [value]="organization.id">
          {{ organization.name }}
        </ng-option>
      </ng-select>
```

![image](https://user-images.githubusercontent.com/19663067/96692869-d7ae4580-1386-11eb-8fa9-60258d11720e.png)


The weird thing is if I delete the "for" in the label and the "labelForId" it is working, or I if delete one of the two or if one is not matching the other. 

Anyone have an idea of why is that ?

ng-select version : 4.0.4
Browser : Chrome

**Comment by jongomes** [comment]
<nz-select formControlName="gateway" nzShowSearch nzAllowClear nzPlaceHolder="pick the gateway"  >

work me
